# Generated by Django 2.1.7 on 2019-03-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='short_description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
