# Generated by Django 2.1.7 on 2019-03-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('supscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='date supscribed')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active subscriber')),
            ],
        ),
    ]
