# Generated by Django 2.1.7 on 2019-04-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='embed_link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='watch_link',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='', max_length=50, verbose_name='Youtube video id'),
        ),
    ]
