# Generated by Django 2.1.7 on 2019-04-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190427_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dummy_image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
